sudo: required
services:
  - docker

before_install:
  - docker build -t repository_name/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run repository_name/react-test npm test -- --coverage

after_success:
  - docker build -t repository_name/fibonacci-client ./client
  - docker build -t repository_name/fibonacci-nginx ./nginx
  - docker build -t repository_name/fibonacci-server ./server
  - docker build -t repository_name/fibonacci-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push repository_name/fibonacci-client
  - docker push repository_name/fibonacci-nginx
  - docker push repository_name/fibonacci-server
  - docker push repository_name/fibonacci-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: fibonacci-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-306476627547
  bucket_path: docker-fibonacci
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY